### ISSUE TITLE
Weave in PageRank operator

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#12]
We are having already a `PageRankOperator` but it needs to be integrated more tightly into the system:
- [ ] Make it part of a dedicated graph plugin.
- [ ] Add a PageRank-to-RheemBasic mapping.
- [ ] Add a GraphX PageRank operator.
- [ ] Add a dedicated Java implementation.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#18
