### ISSUE TITLE
Pass context information to operators on execution

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#17]
When an `ExecutionOperator` gets hold of the `OperatorContext` it can use that information for several aspects:
* a hash join could use cardinality information to find out which side to index and which side to use for probing
* in-loop operators could modify certain configurations based on the current number of iteration

Thus, such context information should be made available to `ExecutionOperator`s.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#20
