### ISSUE TITLE
Allow more actual iterations than expected iterations

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#19]
For the `DoWhileOperator` and `LoopOperator`, Rheem requires an expected number of iterations and then uses this as a basis to estimate the processing time of a plan with loops. However, the produced estimates are also used to (i) provide additional information to `ExecutionOperator`s (e.g., current iteration, `CardinalityEstimate`s) and to (ii) compare actual execution times to time estimates.

In consequence, Rheem crashes when there are more actual than estimated iterations. In turn, Rheem needs to extend the required data structure on-the-fly, as soon as the number of expected iterations increases.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#21
