### ISSUE TITLE
Introduce dedicated "repeat n-times" loop

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#2]
As of now, we can use the `LoopOperator` to emulate a loop that repeats the loop body a given number of times. However, this bloats the actually executed plans by the `ExecutionOperator`s necessary to do the counting, thereby introducing performance overhead, making the optimization harder, and complicating debugging.

With the "repeat n-times" being such a recurring programming pattern (and so far the only real use case for the `LoopOperator`), it is worthwhile to create a dedicated `RepeatLoopOperator` (or similar).

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#12
