### ISSUE TITLE
Add sampling to the APIs

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#20]
We have the `SampleOperator` in the basic plugin, but it's not reflected in the API. It should be added. Also, it would be nice if there was no need to make specifying the sampling method optional.

**Comment by sekruse** [comment]
When `SampleOperator`s lack the dataset size, they materialize the dataset in order to count it. While this is logically sound, it tricks the statistics collection. Thus, it would be better if the `SampleOperator`s exposed that behavior so that Rheem can better keep track of what is happening.

**Comment by sekruse** [comment]
The handling of eager execution and channel evaluation will be postponed.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#22
