### ISSUE TITLE
Add more measurements to experiments

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#23]
To showcase how Rheem has been executed, it should log more statistics to `Experiment`s, for instance:
- [ ] actually executed `ExecutionOperator`s
- [ ] how much time has been spent in each of the `Executor`s
- [ ] or the `PartialExecution`s in the first place
- [ ] measured cardinalities

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#23
