### ISSUE TITLE
Incorporate costs in Rheem

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#27]
When given a bunch of options, Rheem picks that plan implementation that it deems to be the most efficient. While efficiency is an obvious key metric, there might others as well, though, e.g., monetary costs or resource usage. Thus, another indirection should be added that lets Rheem calculate costs.

We shall start with a simple cost function that consists of a linear function over the consumed time per platform.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#25
