### ISSUE TITLE
Add random pruning strategy

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#31]
To gather more, and especially more diverse, execution data for the training of the cost functions, it would be very useful to generate arbitrary `ExecutionPlans`s/`ExecutionTaskFlow`s from a given `RheemPlan`. In general, this can be done by an appropriate instrumentation of the respective Rheem app. A more general approach, though, is to have Rheem create such arbitrary plans. And a simple way to do so is to provide a `PlanEnumerationPruningStrategy` that prunes randomly.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#27
