### ISSUE TITLE
Add cross-platform strategy

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#33]
A simple way to enforce Rheem to not consider cross-platform `ExecutionPlan`s is to add an according `PruningStrategy` that removes such plans already during the enumeration. Such a feature would allow to "degrade" Rheem to an optimizer towards only platform independence, which is interesting for experiments and comparisons.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#28
