### ISSUE TITLE
Account for platform start-up costs

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#4]
In general, platforms might incur some overhead for initialization (e.g., Spark does so). This overhead cannot be pinned to single `Operator`s and can therefore not be expressed in our current cost model. However, it is an important criterion to determine whether to use only Java (no overhead) or some "heavy-weight" framework. Thus, we should model this overhead explicitly:

- [ ] model the overhead as part of `PlanImplementation`s' `TimeEstimate`s
- [ ] in `LatentOperatorPruningStrategy`, treat the usage of a `Platform` as an interesting property (the initial overhead for single `Operator`s might be redeemed over the complete `PlanImplementation`)

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#13
