### ISSUE TITLE
Parallel stages

### ISSUE THREAD

**Issue by atroudi** [daqcri/rheem#40]
This issue is intended to update with stage execution parallelism to execute parallel independent stages inside parallel threads. And also to take into account parallel execution when calculating the plan cost.

**Comment by sekruse** [comment]
This issue proposes to execute topographically unrelated tasks (neither precedes the other) in a Rheem plan in parallel. This involves adapting the execution engine as well as taking to account parallel execution in the optimizer.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#30
