### ISSUE TITLE
Facilitate use of join operator

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#43]
The `JoinOperator` and the method `DataQuanta.join(...)` in particular are a bit tricky to use. This is because (1) it has a lot of inputs, (2) requires to provide type arguments, and (3) the resulting `Tuple2`s must oftentimes be unraveled. It would be nice to offer some clearer interface to joins that mitigates these three issues.

**Comment by sekruse** [comment]
I have built a [different join operator API](https://github.com/stratosphere/metadata-ms/blob/mdms-35/mdms/mdms-analytics/src/main/scala/de/hpi/isg/mdms/analytics/rheem/MetadataQuanta.scala#L64) in a different project, which does not require (i) dealing with `Tuple2`s and (ii) type args. What do you think about this?

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#31
