### ISSUE TITLE
Tag rheem-api artifacts with Scala version

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#44]
The `rheem-api` module uses Scala. For Rheem to integrate well with any libraries that use Scala (such as Spark!) as well, it is necessary to tag the releases of the module with the Scala version. This measure is important to make sure that there is only one Scala library in the classpath and all libraries are compiled against the same Scala library.

**Comment by sekruse** [comment]
Actually, this is not limited to `rheem-api` but any module that depends (transitively) on any Scala project (e.g., `rheem-spark` and `rheem-graphchi`). Given this, we should probably add the major Scala version to _all_ modules.

**Comment by atroudi** [comment]
Quick note regarding this same issue, I faced an issue in `rheem-api` when compiling it with Scala 10, i.e. runnig spark job precompiled with scala 10. I used a workaround by compiling only `rheem-api` with Scala version 11 while the rest of Rheem modules are compiled with Scala version 11.

**Comment by sekruse** [comment]
In general, you should be able to choose with Scala version to use via
```
$ mvn install -Dscala.version=2.1x.y -Dscala.compat.version=2.1x
```
which should already help. And it is in any case advisable to only use a single Scala version for your complete build.

However, if you are going to use the Rheem versions deployed in Maven Central, you don't get to choose, which Scala version to use.

**Comment by sekruse** [comment]
In Flink, this is solved [with bash scripts](https://github.com/apache/flink/blob/master/tools/change-scala-version.sh) that modify the project descriptors. We could follow the same path. Otherwise, we would probably have to change to a different build tool, sbt in particular.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#32
