### ISSUE TITLE
Create generic RDBMS platform

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#7]
So far, Rheem supports PostgreSQL, which entails some issues:

* The code cannot be tested automatically, as it requires PostgreSQL to be installed.
* There are databases other than PostgreSQL, of course.
* Typical issues when supporting more databases: code duplication, maintainability etc.

Therefore, it seems worthwhile to come up with a more generic RDBMS platform template from that specific database platforms can be derived. The basic database access could be generalized via JDBC or Slick.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#15
