### ISSUE TITLE
Introduce plug-ins

### ISSUE THREAD

**Issue by sekruse** [daqcri/rheem#9]
The optimization process of Rheem is currently affected by means of `Platform`s. Those can be registered with a `RheemContext` and all their `ExecutionOperator`s etc. will then be considered when executing a `RheemPlan`. However, this abstraction is not really appropriate as there is a different between platforms and "plug-ins". A platform provides an `Executor` to have specific `ExecutionOperator`s executed. However, neither the `ExecutionOperator`s nor the mappings from `Operator`s to `ExecutionOperator`s nor the `ChannelConversion`s are necessarily described (exhaustively) by a platform.

To this end, we should introduce plug-ins decouple execution platforms from the above mentioned components in Rheem. A plug-in provides `Mapping`s, `ChannelConversion`s, `ExecutionOperator`s, as well as `Configuration` properties and requires `Platform`s. Also, each platform should ship with a "basic" plugin.

**Comment by luckyasser** [comment]
This issue was moved to rheem-ecosystem/rheem#16
